### ISSUE TITLE
Travis is broken because link points to old resource

### ISSUE THREAD

**Issue by cxcorp** [ohtu-intellij/tmc-intellij#107]
From `prepare_build.sh`:
```
mkdir -p target/dependency/intellij-idea
curl -L http://download.jetbrains.com/idea/ideaIC-2016.2.tar.gz | tar xz --strip-components=1 -C target/dependency/intellij-idea
```

The link used is dead. [This article](https://confluence.jetbrains.com/display/IntelliJIDEA/Previous+IntelliJ+IDEA+Releases) suggests that the following link could work instead:

> https://download.jetbrains.com/idea/ideaIU-2016.2.5.tar.gz

**Comment by nygrenh** [comment]
Good catch! Do you want to create a pull request?

**Comment by cxcorp** [comment]
Honestly I have no idea if this would fix the build :smile: 

I had to add a bunch of imports to fix the "missing symbols" errors and get the plugin compile on IDEA 2016.3, so I reckon that would be the proper solution. Perhaps the tar.gz could be changed to point to the latest, 2016.3 version (if that is even available)?

**Comment by nygrenh** [comment]
Yes, it should be changed to point to `2016.3`.

**Comment by cxcorp** [comment]
PR #108 fixes the travis build.
