### ISSUE TITLE
tried to access field com.intellij.diff.tools.util.base.DiffViewerBase.LOG from class fi.helsinki.cs.tmc.intellij.importexercise.NewProjectUtilModified

### ISSUE THREAD

**Issue by lanbeast** [ohtu-intellij/tmc-intellij#119]
Just downloaded the TMC Plugin/Course material for the OOProgramingWithJava-PART1. I get this error and I can't submit the code for testing.

> tried to access field com.intellij.diff.tools.util.base.DiffViewerBase.LOG from class fi.helsinki.cs.tmc.intellij.importexercise.NewProjectUtilModified
> java.lang.IllegalAccessError: tried to access field com.intellij.diff.tools.util.base.DiffViewerBase.LOG from class fi.helsinki.cs.tmc.intellij.importexercise.NewProjectUtilModified
> 	at fi.helsinki.cs.tmc.intellij.importexercise.NewProjectUtilModified.importExercise(NewProjectUtilModified.java:55)
> 	at fi.helsinki.cs.tmc.intellij.importexercise.ExerciseImport.importExercise(ExerciseImport.java:23)
> 	at fi.helsinki.cs.tmc.intellij.io.ProjectOpener.openProject(ProjectOpener.java:42)
> 	at fi.helsinki.cs.tmc.intellij.io.ProjectOpener.openProject(ProjectOpener.java:30)
> 	at fi.helsinki.cs.tmc.intellij.io.ProjectOpener.openProject(ProjectOpener.java:66)
> 	at fi.helsinki.cs.tmc.intellij.ui.projectlist.CourseTabFactory$5.mouseClicked(CourseTabFactory.java:219)
> 	at java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:270)
> 	at java.awt.Component.processMouseEvent(Component.java:6536)
> 	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
> 	at java.awt.Component.processEvent(Component.java:6298)
> 	at java.awt.Container.processEvent(Container.java:2236)
> 	at java.awt.Component.dispatchEventImpl(Component.java:4889)
> 	at java.awt.Container.dispatchEventImpl(Container.java:2294)
> 	at java.awt.Component.dispatchEvent(Component.java:4711)
> 	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
> 	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4534)
> 	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
> 	at java.awt.Container.dispatchEventImpl(Container.java:2280)
> 	at java.awt.Window.dispatchEventImpl(Window.java:2746)
> 	at java.awt.Component.dispatchEvent(Component.java:4711)
> 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
> 	at java.awt.EventQueue.access$500(EventQueue.java:98)
> 	at java.awt.EventQueue$3.run(EventQueue.java:715)
> 	at java.awt.EventQueue$3.run(EventQueue.java:709)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
> 	at java.awt.EventQueue$4.run(EventQueue.java:737)
> 	at java.awt.EventQueue$4.run(EventQueue.java:735)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
> 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
> 	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:827)
> 	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:651)
> 	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
> 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
> 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
> 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
> 	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by cxcorp** [comment]
Which IntelliJ IDEA version are you using? You can check this from Help -> About -> Copy to clipboard

**Comment by line55** [comment]
Hi There, 
Here is the build info:

IntelliJ IDEA 2017.1
Build #IU-171.3780.107, built on March 22, 2017

**Comment by cxcorp** [comment]
Can confirm issue on IDEA 2017.1.

**Comment by LofhJann** [comment]
Confirmed for 2017.1. 
2016.3 works just fine

**Comment by nygrenh** [comment]
Should be fixed in 1.0.5.
