### ISSUE TITLE
Can't run project and packages not showing (IntelliJ)

### ISSUE THREAD

**Issue by kableiv** [ohtu-intellij/tmc-intellij#137]
Im on Windows 10 and my IntelliJ IDEA version is: IU-181.4203.550
And it also worked fine up until a couple of days ago, and I havent messed around with any of the setting of either IntelliJ or the TMC plugin.

First of, everytime I open up an exercise the packages arent showing only the .xml, .mf, .iml and .gitignore. I can temporarily fix this by deleting all the exercise I have downloaded and download them again, but if I close down my pc or Intellij I need to do it again.

Secondly when I finally get everything to show in my Intellij project and try to run the project, I get the following line of error codes:

Information:java: Errors occurred while compiling module 'week4-073.Product'
Information:javac 1.8.0_144 was used to compile java sources
Information:4/17/2018 9:01 AM - Compilation completed with 37 errors and 0 warnings in 1s 578ms
C:\Users\nerdi\OneDrive\Documents\IdeaProjects\TMCProjects\mooc-2013-OOProgrammingWithJava-PART1\week4-073.Product\test\ProductTest.java
Error:(2, 39) java: package fi.helsinki.cs.tmc.edutestutils does not exist
Error:(3, 39) java: package fi.helsinki.cs.tmc.edutestutils does not exist
Error:(4, 39) java: package fi.helsinki.cs.tmc.edutestutils does not exist
Error:(5, 39) java: package fi.helsinki.cs.tmc.edutestutils does not exist
Error:(6, 46) java: package fi.helsinki.cs.tmc.edutestutils.Reflex does not exist
Error:(7, 46) java: package fi.helsinki.cs.tmc.edutestutils.Reflex does not exist
Error:(11, 17) java: package org.junit does not exist
Error:(12, 17) java: package org.junit does not exist
Error:(13, 24) java: package org.junit does not exist
Error:(15, 2) java: cannot find symbol
  symbol: class Points
Error:(18, 11) java: package Reflex does not exist
Error:(21, 6) java: cannot find symbol
  symbol:   class Before
  location: class ProductTest
Error:(26, 6) java: cannot find symbol
  symbol:   class Test
  location: class ProductTest
Error:(31, 6) java: cannot find symbol
  symbol:   class Test
  location: class ProductTest
Error:(39, 6) java: cannot find symbol
  symbol:   class Test
  location: class ProductTest
Error:(44, 6) java: cannot find symbol
  symbol:   class Test
  location: class ProductTest
Error:(62, 6) java: cannot find symbol
  symbol:   class Test
  location: class ProductTest
Error:(78, 6) java: cannot find symbol
  symbol:   class Test
  location: class ProductTest
Error:(23, 17) java: cannot find symbol
  symbol:   variable Reflex
  location: class ProductTest
Error:(33, 15) java: package Reflex does not exist
Error:(46, 15) java: package Reflex does not exist
Error:(46, 46) java: cannot find symbol
  symbol:   variable Reflex
  location: class ProductTest
Error:(54, 13) java: cannot find symbol
  symbol:   method fail(java.lang.String)
  location: class ProductTest
Error:(64, 9) java: cannot find symbol
  symbol:   class MockInOut
  location: class ProductTest
Error:(64, 29) java: cannot find symbol
  symbol:   class MockInOut
  location: class ProductTest
Error:(73, 9) java: cannot find symbol
  symbol:   method assertTrue(java.lang.String,boolean)
  location: class ProductTest
Error:(74, 9) java: cannot find symbol
  symbol:   method assertTrue(java.lang.String,boolean)
  location: class ProductTest
Error:(75, 9) java: cannot find symbol
  symbol:   method assertTrue(java.lang.String,boolean)
  location: class ProductTest
Error:(81, 9) java: cannot find symbol
  symbol:   class MockInOut
  location: class ProductTest
Error:(81, 29) java: cannot find symbol
  symbol:   class MockInOut
  location: class ProductTest
Error:(88, 9) java: cannot find symbol
  symbol:   method assertTrue(java.lang.String,boolean)
  location: class ProductTest
Error:(89, 9) java: cannot find symbol
  symbol:   method assertTrue(java.lang.String,boolean)
  location: class ProductTest
Error:(90, 9) java: cannot find symbol
  symbol:   method assertTrue(java.lang.String,boolean)
  location: class ProductTest
Error:(96, 26) java: cannot find symbol
  symbol:   variable ReflectionUtils
  location: class ProductTest
Error:(99, 13) java: cannot find symbol
  symbol:   method assertFalse(java.lang.String,boolean)
  location: class ProductTest
Error:(100, 13) java: cannot find symbol
  symbol:   method assertTrue(java.lang.String,boolean)
  location: class ProductTest
Error:(110, 13) java: cannot find symbol
  symbol:   method assertTrue(java.lang.String,boolean)
  location: class ProductTest

**Comment by nygrenh** [comment]
Many people have gotten this kind of problem when using OneDrive. If you
move your project folder out of OneDrive, everything out should start
working again.

**Comment by kableiv** [comment]
Thx, moved the folder and it works now.
