### ISSUE TITLE
error: lambda expressions are not supported in -source 6

### ISSUE THREAD

**Issue by jenni** [ohtu-intellij/tmc-intellij#140]
Getting this error when using:

```
    public void printMeals() {
        this.meals.forEach(meal -> System.out.println(meal));
    }
```

It'd be nice if TMC supported Java 8 features :)

**Comment by rlmhermans** [comment]
That is not so much up to TMC, as it is to the project file owners.

**Comment by nygrenh** [comment]
Closing this as it is a duplicate of https://github.com/materiaalit/2013-oo-programming/issues/1
